#!/bin/bash

help() {
  cat <<"EOF"
##########################
# bigit usage :
# eval "$(docker run --rm lalyos/bigit --functions)"
##########################
EOF
}

[[ $# == 0 ]] && help

case $1 in
  --help)
      help
      ;;

  --functions)
      sed '/main()/,$ d' /bin/bigit-functions
      ;;

  *)
    /bin/git-receive "$@"
    ;;
esac
