#!/bin/sh

echo ==== TOP ${BIGIT_TOP:=10} BIG FILES:

git rev-list --objects --all | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' | awk '/^blob/ {print substr($0,6)}'| sort --numeric-sort --reverse --key=2|sed "s/\(^.\{10\}\).\{30\}/\1/" | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest|head -${BIGIT_TOP}
